openapi: 3.0.0
info:
  title: Education API
  version: 1.0.0
  description: API for managing assignments, submissions, feedback, and user authentication.
servers:
  - url: http://localhost:8000
paths:
  /users/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: integer
                  enum: [0, 1, 2] # ADMIN, LECTURER, STUDENT
      responses:
        '201':
          description: User created successfully
        '409':
          description: Email already exists
        '400':
          description: Invalid input

  /users/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Authentication failed

  /assignments:
    get:
      summary: Get all assignments
      responses:
        '200':
          description: A list of assignments
        '404':
          description: No assignments found

    post:
      summary: Create a new assignment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                subject:
                  type: string
                due_date:
                  type: string
                  format: date
      responses:
        '201':
          description: Assignment created successfully
        '400':
          description: Invalid input

  /assignments/{assignmentId}:
    get:
      summary: Get an assignment by ID
      parameters:
        - name: assignmentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Assignment found
        '404':
          description: No valid entry found for the provided ID

    put:
      summary: Update an assignment
      parameters:
        - name: assignmentId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                subject:
                  type: string
                due_date:
                  type: string
                  format: date
      responses:
        '200':
          description: Assignment updated successfully
        '404':
          description: No valid entry found for the provided ID

    delete:
      summary: Delete an assignment
      parameters:
        - name: assignmentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Assignment deleted successfully
        '404':
          description: No valid entry found for the provided ID

  /submissions:
    get:
      summary: Get all submissions
      responses:
        '200':
          description: A list of submissions
        '404':
          description: No submissions found

    post:
      summary: Submit a video
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                video:
                  type: string
                  format: binary
                assignmentId:
                  type: string
                userId:
                  type: string
      responses:
        '201':
          description: Video submitted successfully
        '400':
          description: Invalid input

  /submissions/{submissionId}:
    get:
      summary: Get a submission by ID
      parameters:
        - name: submissionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Submission found
        '404':
          description: No submission found with the provided ID

    delete:
      summary: Delete a submission
      parameters:
        - name: submissionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Submission deleted successfully
        '404':
          description: No submission found with the provided ID

  /feedback:
    post:
      summary: Provide feedback on a submission
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                submissionId:
                  type: string
                feedback:
                  type: string
                marks:
                  type: number
                lecturerId:
                  type: string
      responses:
        '200':
          description: Feedback provided successfully
        '404':
          description: Submission not found

    get:
      summary: Get feedbacks for a specific assignment
      parameters:
        - name: assignmentId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of feedbacks
        '404':
          description: No feedback found for this assignment

components:
  schemas:
    User:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: integer
    Assignment:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        subject:
          type: string
        due_date:
          type: string
          format: date
    Submission:
      type: object
      properties:
        assignment:
          type: string
        student:
          type: string
        videoPath:
          type: string
        feedbackBy:
          type: string
        submittedAt:
          type: string
          format: date-time
    Feedback:
      type: object
      properties:
        videoId:
          type: string
        userId:
          type: string
        feedbackText:
          type: string
        mark:
          type: number