openapi: 3.0.0
info:
  title: Student Konnekt API
  version: 1.0.0
  description: API documentation for the Home Management System, covering user authentication, assignments, feedback, submissions, and video management.

servers:
  - url: http://localhost:8000/api/v1
    description: Local development server

paths:
  /users/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  example: "John"
                last_name:
                  type: string
                  example: "Doe"
                email:
                  type: string
                  format: email
                  example: "john.doe@example.com"
                password:
                  type: string
                  example: "P@ssw0rd123"
                role:
                  type: integer
                  enum: [0, 1, 2] # ADMIN, LECTURER, STUDENT
                  example: 2
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User registered successfully"
                  userId:
                    type: string
                    example: "64f4da5e0a34f9b0a45bf34a"
        '400':
          description: Invalid input
        '409':
          description: Email already exists

  /users/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: "john.doe@example.com"
                password:
                  type: string
                  example: "P@ssw0rd123"
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Login successful"
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
        '401':
          description: Authentication failed

  /users/{userId}:
    delete:
      summary: Delete a user
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user to delete
          schema:
            type: string
            example: "64f4da5e0a34f9b0a45bf34a"
      responses:
        '200':
          description: User deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User deleted successfully"
        '404':
          description: User not found

  /assignments:
    get:
      summary: Get all assignments
      responses:
        '200':
          description: A list of assignments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Assignment'

    post:
      summary: Create a new assignment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Math Homework"
                description:
                  type: string
                  example: "Complete the exercises in chapter 3"
                subject:
                  type: string
                  example: "Mathematics"
                due_date:
                  type: string
                  format: date
                  example: "2024-10-05"
      responses:
        '201':
          description: Assignment created successfully
        '400':
          description: Invalid input

  /assignments/{assignmentId}:
    get:
      summary: Get an assignment by ID
      parameters:
        - name: assignmentId
          in: path
          required: true
          description: ID of the assignment to retrieve
          schema:
            type: string
            example: "64f4df5b0a34f9b0a45bf34e"
      responses:
        '200':
          description: Assignment details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Assignment'
        '404':
          description: Assignment not found

  /feedback:
    post:
      summary: Create feedback for an assignment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                assignmentId:
                  type: string
                  example: "64f4df5b0a34f9b0a45bf34e"
                lecturer:
                  type: string
                  example: "Dr. Smith"
                feedback:
                  type: string
                  example: "Good job, but needs more detail on question 3."
                mark:
                  type: number
                  example: 85
      responses:
        '201':
          description: Feedback created successfully
        '400':
          description: Invalid input

  /feedback/{assignmentId}/download:
    get:
      summary: Download marks and feedback for a specific assignment
      parameters:
        - name: assignmentId
          in: path
          required: true
          description: ID of the assignment to download feedback for
          schema:
            type: string
            example: "64f4df5b0a34f9b0a45bf34e"
      responses:
        '200':
          description: Marks and feedback downloaded successfully
        '404':
          description: No feedback found for this assignment

  /submissions:
    post:
      summary: Submit a video for an assignment
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                assignmentId:
                  type: string
                  example: "64f4df5b0a34f9b0a45bf34e"
                userId:
                  type: string
                  example: "64f4da5e0a34f9b0a45bf34a"
                video:
                  type: string
                  format: binary
      responses:
        '201':
          description: Video submitted successfully
        '400':
          description: Invalid input

  /submissions/{submissionId}/stream:
    get:
      summary: Stream a video submission
      parameters:
        - name: submissionId
          in: path
          required: true
          description: ID of the submission to stream
          schema:
            type: string
            example: "64f4e2ac0a34f9b0a45bf350"
      responses:
        '200':
          description: Video streaming successfully
        '404':
          description: Submission not found

components:
  schemas:
    Assignment:
      type: object
      properties:
        _id:
          type: string
          example: "64f4df5b0a34f9b0a45bf34e"
        title:
          type: string
          example: "Math Homework"
        description:
          type: string
          example: "Complete the exercises in chapter 3"
        subject:
          type: string
          example: "Mathematics"
        due_date:
          type: string
          format: date
          example: "2024-10-05"
        createdAt:
          type: string
          format: date-time
          example: "2024-09-21T18:25:43.511Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-09-23T10:12:34.511Z"
