openapi: 3.0.0
info:
  title: Feedback API
  description: API for managing feedback
  version: 1.0.0
paths:
  /feedbacks:
    get:
      summary: Retrieve all feedbacks
      responses:
        '200':
          description: A list of feedbacks
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    assignmentId:
                      type: string
                      example: "64d6b0f5b9f1f3a5d6d0e7f2"
                    lecturer:
                      type: string
                      example: "Dr. Tiny DU TOIT"
                    feedback:
                      type: string
                      example: "YOU JUST MADE IT BUDDY WELL DONE!"
                description: A list of feedback objects
        '500':
          description: Server error

  /feedback/assignment/{id}:
    get:
      summary: Retrieve feedback by assignment ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Feedback retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    assignmentId:
                      type: string
                    feedback:
                      type: string
                    lecturer:
                      type: string
        '404':
          description: Feedback not found
        '500':
          description: Server error

  /feedback/{id}:
    get:
      summary: Get feedback by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Feedback retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  assignmentId:
                    type: string
                  feedback:
                    type: string
                  lecturer:
                    type: string
        '404':
          description: Feedback not found
        '500':
          description: Server error

    put:
      summary: Update feedback by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                feedback:
                  type: string
                  example: "Updated feedback text"
                lecturer:
                  type: string
                  example: "Updated lecturer name"
      responses:
        '200':
          description: Feedback updated successfully
        '404':
          description: Feedback not found
        '500':
          description: Server error

    delete:
      summary: Delete feedback by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Feedback deleted successfully
        '404':
          description: Feedback not found
        '500':
          description: Server error